### PR TITLE
feat(UI): impl localization

### LINKED ISSUE #12: Localization

### PR DESCRIPTION
**Pull request by baka-gourd**
resolve #12 
@kendallroth

### CODE REVIEW

**Comment by kendallroth** [comment]
Thank you so much for your contribution! I will take a look at this tomorrow! ♥️

**Comment by baka-gourd** [comment]
> Thank you so much for your contribution! I will take a look at this tomorrow! ♥️

hello?

**Comment by kendallroth** [comment]
> > Thank you so much for your contribution! I will take a look at this tomorrow! ♥️
> 
> hello?

Unfortunately I was unable to take a look before some vacation, but will be picking back up as I resume with CS2 (hopefully shortly)

**Comment by kendallroth** [comment]
Thanks for this contribution! I'm going to move it into a `localization` branch and add some locale file loading, and also add you as a contributor. Thanks again!

**Comment by kendallroth** [comment]
I wound up spending a while agonizing over localization key naming, and wound up going with a slightly different approach than either the vanilla keys (which are honestly just all over the place) or the current community recommendation (although this is the closest inspiration). Also realized that the `"hidden"` tooltip modifier (for hidden stats) was not being translated, and updated.

I also just (after said changes...) realized that your "I18NEverywhere" mod has built-in translations (didn't really grasp that before), and apologize for the changed key structure... However, I am planning on keeping the new structure as it more closely aligns with how I handle localization in other projects (ie. the structure is similar to a JSON file, with `[]` for dynamic keys and `.` for static keys).

All that being said, thank you again so much for your willingness to contribute to localization ❤️! I hope this change won't be too much of a bother, but I'm also not entirely certain how "I18NEverywhere" works alongside mods that provide their own localizations? I'm experimenting with CrowdIn support just to learn how it works, but am guessing that it will never take off as much as your mod/translations, so curious on the interopability there (is that what the mod's "override" setting is for)?

**Comment by baka-gourd** [comment]
> I wound up spending a while agonizing over localization key naming, and wound up going with a slightly different approach than either the vanilla keys (which are honestly just all over the place) or the current community recommendation (although this is the closest inspiration). Also realized that the `"hidden"` tooltip modifier (for hidden stats) was not being translated, and updated.

There is no specification for what key format must be used, but I don't think anyone is going to use a meaningless key

> I also just (after said changes...) realized that your "I18NEverywhere" mod has built-in translations (didn't really grasp that before), and apologize for the changed key structure... However, I am planning on keeping the new structure as it more closely aligns with how I handle localization in other projects (ie. the structure is similar to a JSON file, with `[]` for dynamic keys and `.` for static keys).

No need to worry, it's just a file I added in my testing and didn't release

> (ie. the structure is similar to a JSON file, with `[]` for dynamic keys and `.` for static keys).

Of course, if you don't use the simple key-value pair i18n can't handle it

i18neverywhere has a feature in the game that makes it easy to export all key values, so there's no need to worry about updating, it's basically an instantaneous thing

> All that being said, thank you again so much for your willingness to contribute to localization ❤️! I hope this change won't be too much of a bother, but I'm also not entirely certain how "I18NEverywhere" works alongside mods that provide their own localizations? I'm experimenting with CrowdIn support just to learn how it works, but am guessing that it will never take off as much as your mod/translations, so curious on the interopability there (is that what the mod's "override" setting is for)?

You can use crowdin to host the translations yourself, and I recommend doing so :) If you want to use i18n to load language files, you'll need to add the `lang` folder in your output directory and put the json for the corresponding language in it, adding i18n as a dependency while not changing the code.

image

The loading will be done by the i18n.

`override` is only used to fix some incorrect translations (which we all know CO sometimes doesn't do well), this will allow to override the in-game translations using the translations loaded by i18n.

example: https://github.com/Cmyna/BetterMoonLight

**Comment by kendallroth** [comment]
> Of course, if you don't use the simple key-value pair i18n can't handle it

Oh yeah, it's still using key/value string pairings, but just in a pseudo-JSON format I am a little more familiar with.

`"CityStats.ToolbarActions[TogglePanel].TooltipTitle": "City Stats"`

> i18neverywhere has a feature in the game that makes it easy to export all key values, so there's no need to worry about updating, it's basically an instantaneous thing

I actually just noticed this in the settings for the mod; nice 🎉!

> You can use crowdin to host the translations yourself, and I recommend doing so :) If you want to use i18n to load language files, you'll need to add the `lang` folder in your output directory and put the json for the corresponding language in it, adding i18n as a dependency while not changing the code.

Yeah, I setup a CrowdIn project and was messing around with it, but it will be a trial-by-fire process 🙂... I wish there was a way to generate the machine translations as "unapproved", but then I guess they would require manual verification before they would be included in the generated download (at least, assuming that's how that works)... However, it's at least setup and noted in the `PublishConfiguration.xml` (and now `README` also), so we will see what happens with it.

Currently I have the locale files within `Localization/Locales/`, as I found inspiration in the "Traffic" mod for a quick way of loading dictionaries from local JSON files into CS2 translation manager. However, maybe I should check whether this will cause any issues with I18Everywhere (or whether I'm completely misunderstanding its purpose...)? If I provide only _some_ languages through the mod, will others potentially be loaded from I18Everywhere (ie. Korean)? What would happen with the langauges that are specified in this mod; would they cause any conflict with the ones now included in I18Everywhere?

**Comment by baka-gourd** [comment]
nope, i18n only care about lang folder, use locales folder have no problem. And it will not cause any problems.

**Pull request merged**
